-- Baseline: espelha o schema já existente (gerado até aqui pelo ddl-auto do Hibernate),
-- para o Flyway assumir o controle do schema a partir daqui.

CREATE TABLE user_entity (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    permission_id BIGINT,
    created_at    TIMESTAMP,
    update_at     TIMESTAMP,
    active        BOOLEAN NOT NULL,
    CONSTRAINT uk_user_entity_email UNIQUE (email)
);

CREATE TABLE categorias (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE documentation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255),
    content      TEXT,
    categoria_id BIGINT NOT NULL,
    created_by   VARCHAR(255),
    update_by    VARCHAR(255),
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    status       VARCHAR(255),
    CONSTRAINT fk_documentation_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id)
);

CREATE TABLE arquivo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255),
    stored_name   VARCHAR(255),
    mime_type     VARCHAR(255),
    extension     VARCHAR(255),
    size          BIGINT,
    path          VARCHAR(255),
    upload_date   TIMESTAMP
);

CREATE TABLE conversation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE conversation_file (
    conversation_id BIGINT NOT NULL,
    file_id         BIGINT NOT NULL,
    CONSTRAINT fk_conversation_file_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id),
    CONSTRAINT fk_conversation_file_file FOREIGN KEY (file_id) REFERENCES arquivo (id)
);

CREATE TABLE chat (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
