-- Organiza os documentos por categoria e restringe o acesso de EDITOR/USUARIO às categorias
-- em que estiverem cadastrados. ADMIN continua com acesso irrestrito (ver CategoriaAccessService).

-- "documentation" era o módulo legado (CRUD simples, sem RAG/versionamento) removido do
-- código nesta mesma entrega — a tabela não tem mais nenhuma entidade JPA mapeando ela.
DROP TABLE IF EXISTS documentation;

ALTER TABLE documento ADD COLUMN categoria_id BIGINT;
ALTER TABLE documento ADD CONSTRAINT fk_documento_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id);
CREATE INDEX idx_documento_categoria_id ON documento (categoria_id);

-- Carrega a categoria da proposta junto com o rascunho: na criação, a IA escolhe entre as
-- categorias do usuário; na atualização, é sempre a categoria vigente do documento-alvo.
ALTER TABLE documento_rascunho ADD COLUMN categoria_id BIGINT;

CREATE TABLE usuario_categoria (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    CONSTRAINT fk_usuario_categoria_usuario FOREIGN KEY (usuario_id) REFERENCES user_entity (id),
    CONSTRAINT fk_usuario_categoria_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT uk_usuario_categoria UNIQUE (usuario_id, categoria_id)
);

CREATE INDEX idx_usuario_categoria_usuario_id ON usuario_categoria (usuario_id);
