-- Propostas de criação de categoria feitas pela IA no chat (ver CategoriaTools), para quando
-- nenhuma categoria existente serve para o documento que está sendo criado/atualizado - segue
-- o mesmo princípio dos rascunhos de documento: só confirma em um turno de conversa posterior
-- ao turno em que foi proposta, e criar categoria de verdade continua ADMIN-only (CategoryService
-- aplica essa regra na confirmação).

CREATE TABLE categoria_rascunho (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversa_id   UUID NOT NULL,
    nome          VARCHAR(255) NOT NULL,
    descricao     VARCHAR(255),
    status        VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    turno_criacao UUID NOT NULL,
    criado_em     TIMESTAMP NOT NULL,
    confirmado_em TIMESTAMP,
    CONSTRAINT fk_categoria_rascunho_conversa FOREIGN KEY (conversa_id) REFERENCES chat_conversa (id)
);

CREATE INDEX idx_categoria_rascunho_conversa_status ON categoria_rascunho (conversa_id, status);
